version: '3.5'

services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "6565:6565"
      - "8080:8080"
    environment:
      - AB_BASE_URL
      - AB_CLIENT_ID
      - AB_CLIENT_SECRET
      - AB_NAMESPACE
      - GRPC_VERBOSITY=debug
      - LOKI_URL=http://host.docker.internal:3100/loki/api/v1/push
      - OTEL_EXPORTER_ZIPKIN_ENDPOINT=http://host.docker.internal:9411/api/v2/spans
    logging:
      driver: loki
      options:
        loki-url: http://host.docker.internal:3100/loki/api/v1/push
        mode: non-blocking
        max-buffer-size: 4m
        loki-retries: "3"
    extra_hosts:
      - host.docker.internal:host-gateway